Name                    = "Wordpress"
Env                     = "Dev"
Created_by              = "Vova"
Dept                    = "IT"
ami                     = "ami-0862aabda3fb488b5"
instance_type           = "t2.micro"
key_name                = "vova mac"