Name                    = "Wordpress"
Env                     = "Dev"
Created_by              = "Vova"
Dept                    = "IT"
ami                     = "ami-0c5c15d56ae86fb8f"
instance_type           = "t2.micro"
key_name                = "vova mac"